#!/usr/bin/env bash
set -euo pipefail

CONFIG_PATH="/etc/srkbz/config-apt.env"

function main {
    exit-if-config-already-exists

    log-sep

    ask-for "APT domain" aptDomain
    write-config \
        "APT_DOMAIN" "$aptDomain"

    log-sep
}

function exit-if-config-already-exists {
    if [ -f "${CONFIG_PATH}" ]; then
        exit 0
    fi
}

function ask-for {
    printf "%s: " "$1"
    read -r "$2"
}

function write-config {
    mkdir -p "$(dirname ${CONFIG_PATH})"
    printf "%s=%s\n" "$@" > $CONFIG_PATH
}

function log-sep {
    printf "\n"
}

main "$@"
