#!/usr/bin/env bash
set -euo pipefail

jarfile="$(cat ./minecraft_jarfile)"
total_memory="$(grep MemTotal /proc/meminfo | awk '{print $2}')"
memory="$(qjs --std -e "std.puts(Math.round(${total_memory} * 0.4))")"

printf "%s: %s\n" \
	"JAR file" "${jarfile}" \
	"System memory" "${total_memory}k" \
	"Memory assigned to Java process" "${memory}k"

# Aikar's Flags
# https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/
java \
	"-Xms${memory}k" "-Xmx${memory}k" -XX:+UseG1GC -XX:+ParallelRefProcEnabled \
	-XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions \
	-XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 \
	-XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 \
	-XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 \
	-XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 \
	-XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 \
	-XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 \
	-Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true \
	-jar "${jarfile}" nogui
