#!/usr/bin/env bash
set -euo pipefail

CONFIG_PATH="/etc/srkbz/config-base.env"

function main {
    exit-if-config-already-exists

    log-sep

    ask-for "Monitoring domain" monitoringDomain
    ask-for "Monitoring secret path" monitoringSecretPath
    write-config \
        "MONITORING_DOMAIN" $monitoringDomain \
        "MONITORING_SECRET_PATH" $monitoringSecretPath

    log-sep
}

function exit-if-config-already-exists {
    if [ -f "${CONFIG_PATH}" ]; then
        exit 0
    fi
}

function ask-for {
    printf "$1: "
    read -r $2
}

function write-config {
    mkdir -p "$(dirname ${CONFIG_PATH})"
    printf "%s=%s\n" $@ > $CONFIG_PATH
}

function log-sep {
    printf "\n"
}

main "$@"
